name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+141

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  date_picker_timeline: ^1.2.5

  material_design_icons_flutter: ^5.0.6996
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.1
  device_info_plus: ^9.0.3
  connectivity_plus: ^4.0.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  email_validator: ^2.1.17
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  dio: ^5.3.3
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  jiffy: ^6.2.1
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  mobile_number: ^2.1.1
  sms_autofill: ^2.3.0
  otp_autofill: ^3.0.0
  # flutter_facebook_auth: ^6.0.2
  # google_sign_in: ^6.1.5
  cached_network_image: ^3.3.0
  fdottedline_nullsafety: ^2.0.1
#  geolocator: ^10.1.0
  shimmer: ^3.0.0
  scratcher: ^2.4.0
  razorpay_flutter: ^1.3.5
#  geocoding: ^2.1.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.0.0+1
  mapbox_search: ^3.2.0
#  google_maps_flutter: ^2.5.0
  flutter_mapbox_autocomplete: ^2.0.0
  flutter_paystack: ^1.0.7
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  provider: ^6.0.5
  photo_view: ^0.14.0
  flutter_toggle_tab: ^1.4.1
  # sign_in_with_apple: ^5.0.0
#  flutter_google_places: ^0.3.0
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_svg: ^1.0.3
  intl: ^0.18.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  background_color: "#FFFFFF"
  image_path: "assets/images/1024.png"
  adaptive_icon_foreground: "assets/images/1024.png"
  adaptive_icon_background: "#FFFFFF"
#  image_path: "assets/roundicon.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
        # - asset: assets/fonts/Poppins-BlackItalic.otf
        # - asset: assets/fonts/Poppins-Bold.otf
        # - asset: assets/fonts/Poppins-BoldItalic.otf
        # - asset: assets/fonts/Poppins-ExtraBold.otf
        # - asset: assets/fonts/Poppins-ExtraBoldItalic.otf
        # - asset: assets/fonts/Poppins-ExtraLight.otf
        # - asset: assets/fonts/Poppins-ExtraLightItalic.otf
        # - asset: assets/fonts/Poppins-Italic.otf
        # - asset: assets/fonts/Poppins-Light.otf
        # - asset: assets/fonts/Poppins-LightItalic.otf
        # - asset: assets/fonts/Poppins-Medium.otf
        # - asset: assets/fonts/Poppins-MediumItalic.otf
        # - asset: assets/fonts/Poppins-Regular.otf
        # - asset: assets/fonts/Poppins-SemiBold.otf
        # - asset: assets/fonts/Poppins-SemiBoldItalic.otf
        # - asset: assets/fonts/Poppins-Thin.otf
        # - asset: assets/fonts/Poppins-ThinItalic.otf
        
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
